<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net10.0-windows</TargetFrameworks>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageReference Include="NUnit" Version="4.5.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlaUI.Core\FlaUI.Core.csproj" />
    <ProjectReference Include="..\FlaUI.TestUtilities\FlaUI.TestUtilities.csproj" />
    <ProjectReference Include="..\FlaUI.UIA2\FlaUI.UIA2.csproj" />
    <ProjectReference Include="..\FlaUI.UIA3\FlaUI.UIA3.csproj" />
    <ProjectReference Include="..\TestApplications\WinFormsApplication\WinFormsApplication.csproj" />
    <ProjectReference Include="..\TestApplications\WpfApplication\WpfApplication.csproj">
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>

</Project>
