using UIA = interop.UIAutomationCore;

namespace FlaUI.UIA3.Definitions
{
    public enum ControlType
    {
        AppBar = UIA.UIA_ControlTypeIds.UIA_AppBarControlTypeId,
        Button = UIA.UIA_ControlTypeIds.UIA_ButtonControlTypeId,
        Calendar = UIA.UIA_ControlTypeIds.UIA_CalendarControlTypeId,
        CheckBox = UIA.UIA_ControlTypeIds.UIA_CheckBoxControlTypeId,
        ComboBox = UIA.UIA_ControlTypeIds.UIA_ComboBoxControlTypeId,
        Custom = UIA.UIA_ControlTypeIds.UIA_CustomControlTypeId,
        DataGrid = UIA.UIA_ControlTypeIds.UIA_DataGridControlTypeId,
        DataItem = UIA.UIA_ControlTypeIds.UIA_DataItemControlTypeId,
        Document = UIA.UIA_ControlTypeIds.UIA_DocumentControlTypeId,
        Edit = UIA.UIA_ControlTypeIds.UIA_EditControlTypeId,
        Group = UIA.UIA_ControlTypeIds.UIA_GroupControlTypeId,
        Header = UIA.UIA_ControlTypeIds.UIA_HeaderControlTypeId,
        HeaderItem = UIA.UIA_ControlTypeIds.UIA_HeaderItemControlTypeId,
        Hyperlink = UIA.UIA_ControlTypeIds.UIA_HyperlinkControlTypeId,
        Image = UIA.UIA_ControlTypeIds.UIA_ImageControlTypeId,
        List = UIA.UIA_ControlTypeIds.UIA_ListControlTypeId,
        ListItem = UIA.UIA_ControlTypeIds.UIA_ListItemControlTypeId,
        MenuBar = UIA.UIA_ControlTypeIds.UIA_MenuBarControlTypeId,
        Menu = UIA.UIA_ControlTypeIds.UIA_MenuControlTypeId,
        MenuItem = UIA.UIA_ControlTypeIds.UIA_MenuItemControlTypeId,
        Pane = UIA.UIA_ControlTypeIds.UIA_PaneControlTypeId,
        ProgressBar = UIA.UIA_ControlTypeIds.UIA_ProgressBarControlTypeId,
        RadioButton = UIA.UIA_ControlTypeIds.UIA_RadioButtonControlTypeId,
        ScrollBar = UIA.UIA_ControlTypeIds.UIA_ScrollBarControlTypeId,
        SemanticZoom = UIA.UIA_ControlTypeIds.UIA_SemanticZoomControlTypeId,
        Separator = UIA.UIA_ControlTypeIds.UIA_SeparatorControlTypeId,
        Slider = UIA.UIA_ControlTypeIds.UIA_SliderControlTypeId,
        Spinner = UIA.UIA_ControlTypeIds.UIA_SpinnerControlTypeId,
        SplitButton = UIA.UIA_ControlTypeIds.UIA_SplitButtonControlTypeId,
        StatusBar = UIA.UIA_ControlTypeIds.UIA_StatusBarControlTypeId,
        Tab = UIA.UIA_ControlTypeIds.UIA_TabControlTypeId,
        TabItem = UIA.UIA_ControlTypeIds.UIA_TabItemControlTypeId,
        Table = UIA.UIA_ControlTypeIds.UIA_TableControlTypeId,
        Text = UIA.UIA_ControlTypeIds.UIA_TextControlTypeId,
        Thumb = UIA.UIA_ControlTypeIds.UIA_ThumbControlTypeId,
        TitleBar = UIA.UIA_ControlTypeIds.UIA_TitleBarControlTypeId,
        ToolBar = UIA.UIA_ControlTypeIds.UIA_ToolBarControlTypeId,
        ToolTip = UIA.UIA_ControlTypeIds.UIA_ToolTipControlTypeId,
        Tree = UIA.UIA_ControlTypeIds.UIA_TreeControlTypeId,
        TreeItem = UIA.UIA_ControlTypeIds.UIA_TreeItemControlTypeId,
        Window = UIA.UIA_ControlTypeIds.UIA_WindowControlTypeId,
    }
}
