using interop.UIAutomationCore;

namespace FlaUI.Core.Definitions
{
    public enum ControlType
    {
        AppBar = UIA_ControlTypeIds.UIA_AppBarControlTypeId,
        Button = UIA_ControlTypeIds.UIA_ButtonControlTypeId,
        Calendar = UIA_ControlTypeIds.UIA_CalendarControlTypeId,
        CheckBox = UIA_ControlTypeIds.UIA_CheckBoxControlTypeId,
        ComboBox = UIA_ControlTypeIds.UIA_ComboBoxControlTypeId,
        Custom = UIA_ControlTypeIds.UIA_CustomControlTypeId,
        DataGrid = UIA_ControlTypeIds.UIA_DataGridControlTypeId,
        DataItem = UIA_ControlTypeIds.UIA_DataItemControlTypeId,
        Document = UIA_ControlTypeIds.UIA_DocumentControlTypeId,
        Edit = UIA_ControlTypeIds.UIA_EditControlTypeId,
        Group = UIA_ControlTypeIds.UIA_GroupControlTypeId,
        Header = UIA_ControlTypeIds.UIA_HeaderControlTypeId,
        HeaderItem = UIA_ControlTypeIds.UIA_HeaderItemControlTypeId,
        Hyperlink = UIA_ControlTypeIds.UIA_HyperlinkControlTypeId,
        Image = UIA_ControlTypeIds.UIA_ImageControlTypeId,
        List = UIA_ControlTypeIds.UIA_ListControlTypeId,
        ListItem = UIA_ControlTypeIds.UIA_ListItemControlTypeId,
        MenuBar = UIA_ControlTypeIds.UIA_MenuBarControlTypeId,
        Menu = UIA_ControlTypeIds.UIA_MenuControlTypeId,
        MenuItem = UIA_ControlTypeIds.UIA_MenuItemControlTypeId,
        Pane = UIA_ControlTypeIds.UIA_PaneControlTypeId,
        ProgressBar = UIA_ControlTypeIds.UIA_ProgressBarControlTypeId,
        RadioButton = UIA_ControlTypeIds.UIA_RadioButtonControlTypeId,
        ScrollBar = UIA_ControlTypeIds.UIA_ScrollBarControlTypeId,
        SemanticZoom = UIA_ControlTypeIds.UIA_SemanticZoomControlTypeId,
        Separator = UIA_ControlTypeIds.UIA_SeparatorControlTypeId,
        Slider = UIA_ControlTypeIds.UIA_SliderControlTypeId,
        Spinner = UIA_ControlTypeIds.UIA_SpinnerControlTypeId,
        SplitButton = UIA_ControlTypeIds.UIA_SplitButtonControlTypeId,
        StatusBar = UIA_ControlTypeIds.UIA_StatusBarControlTypeId,
        Tab = UIA_ControlTypeIds.UIA_TabControlTypeId,
        TabItem = UIA_ControlTypeIds.UIA_TabItemControlTypeId,
        Table = UIA_ControlTypeIds.UIA_TableControlTypeId,
        Text = UIA_ControlTypeIds.UIA_TextControlTypeId,
        Thumb = UIA_ControlTypeIds.UIA_ThumbControlTypeId,
        TitleBar = UIA_ControlTypeIds.UIA_TitleBarControlTypeId,
        ToolBar = UIA_ControlTypeIds.UIA_ToolBarControlTypeId,
        ToolTip = UIA_ControlTypeIds.UIA_ToolTipControlTypeId,
        Tree = UIA_ControlTypeIds.UIA_TreeControlTypeId,
        TreeItem = UIA_ControlTypeIds.UIA_TreeItemControlTypeId,
        Window = UIA_ControlTypeIds.UIA_WindowControlTypeId,
    }
}
