using interop.UIAutomationCore;

namespace FlaUI.Core.Definitions
{
    public enum PropertyType
    {
        // Control Pattern Properties
        GridColumnCount = UIA_PropertyIds.UIA_GridColumnCountPropertyId,
        GridItemColumn = UIA_PropertyIds.UIA_GridItemColumnPropertyId,
        GridItemColumnSpan = UIA_PropertyIds.UIA_GridItemColumnSpanPropertyId,
        GridItemContainingGrid = UIA_PropertyIds.UIA_GridItemContainingGridPropertyId,
        GridItemRow = UIA_PropertyIds.UIA_GridItemRowPropertyId,
        GridItemRowSpan = UIA_PropertyIds.UIA_GridItemRowSpanPropertyId,
        GridRowCount = UIA_PropertyIds.UIA_GridRowCountPropertyId,
        LegacyIAccessibleChildId = UIA_PropertyIds.UIA_LegacyIAccessibleChildIdPropertyId,
        LegacyIAccessibleDefaultAction = UIA_PropertyIds.UIA_LegacyIAccessibleDefaultActionPropertyId,
        LegacyIAccessibleDescription = UIA_PropertyIds.UIA_LegacyIAccessibleDescriptionPropertyId,
        LegacyIAccessibleHelp = UIA_PropertyIds.UIA_LegacyIAccessibleHelpPropertyId,
        LegacyIAccessibleKeyboardShortcut = UIA_PropertyIds.UIA_LegacyIAccessibleKeyboardShortcutPropertyId,
        LegacyIAccessibleName = UIA_PropertyIds.UIA_LegacyIAccessibleNamePropertyId,
        LegacyIAccessibleRole = UIA_PropertyIds.UIA_LegacyIAccessibleRolePropertyId,
        LegacyIAccessibleSelection = UIA_PropertyIds.UIA_LegacyIAccessibleSelectionPropertyId,
        LegacyIAccessibleState = UIA_PropertyIds.UIA_LegacyIAccessibleStatePropertyId,
        LegacyIAccessibleValue = UIA_PropertyIds.UIA_LegacyIAccessibleValuePropertyId,
        MultipleViewCurrentView = UIA_PropertyIds.UIA_MultipleViewCurrentViewPropertyId,
        MultipleViewSupportedViews = UIA_PropertyIds.UIA_MultipleViewSupportedViewsPropertyId,
        RangeValueIsReadOnly = UIA_PropertyIds.UIA_RangeValueIsReadOnlyPropertyId,
        RangeValueLargeChange = UIA_PropertyIds.UIA_RangeValueLargeChangePropertyId,
        RangeValueMaximum = UIA_PropertyIds.UIA_RangeValueMaximumPropertyId,
        RangeValueMinimum = UIA_PropertyIds.UIA_RangeValueMinimumPropertyId,
        RangeValueSmallChange = UIA_PropertyIds.UIA_RangeValueSmallChangePropertyId,
        RangeValueValue = UIA_PropertyIds.UIA_RangeValueValuePropertyId,
        ScrollHorizontallyScrollable = UIA_PropertyIds.UIA_ScrollHorizontallyScrollablePropertyId,
        ScrollHorizontalScrollPercent = UIA_PropertyIds.UIA_ScrollHorizontalScrollPercentPropertyId,
        ScrollHorizontalViewSize = UIA_PropertyIds.UIA_ScrollHorizontalViewSizePropertyId,
        ScrollVerticallyScrollable = UIA_PropertyIds.UIA_ScrollVerticallyScrollablePropertyId,
        ScrollVerticalScrollPercent = UIA_PropertyIds.UIA_ScrollVerticalScrollPercentPropertyId,
        ScrollVerticalViewSize = UIA_PropertyIds.UIA_ScrollVerticalViewSizePropertyId,
        SelectionCanSelectMultiple = UIA_PropertyIds.UIA_SelectionCanSelectMultiplePropertyId,
        SelectionIsSelectionRequired = UIA_PropertyIds.UIA_SelectionIsSelectionRequiredPropertyId,
        SelectionSelection = UIA_PropertyIds.UIA_SelectionSelectionPropertyId,
        SelectionItemIsSelected = UIA_PropertyIds.UIA_SelectionItemIsSelectedPropertyId,
        SelectionItemSelectionContainer = UIA_PropertyIds.UIA_SelectionItemSelectionContainerPropertyId,
        SpreadsheetItemFormula = UIA_PropertyIds.UIA_SpreadsheetItemFormulaPropertyId,
        SpreadsheetItemAnnotationObjects = UIA_PropertyIds.UIA_SpreadsheetItemAnnotationObjectsPropertyId,
        SpreadsheetItemAnnotationTypes = UIA_PropertyIds.UIA_SpreadsheetItemAnnotationTypesPropertyId,
        StylesExtendedProperties = UIA_PropertyIds.UIA_StylesExtendedPropertiesPropertyId,
        StylesFillColor = UIA_PropertyIds.UIA_StylesFillColorPropertyId,
        StylesFillPatternColor = UIA_PropertyIds.UIA_StylesFillPatternColorPropertyId,
        StylesFillPatternStyle = UIA_PropertyIds.UIA_StylesFillPatternStylePropertyId,
        StylesShape = UIA_PropertyIds.UIA_StylesShapePropertyId,
        StylesStyleId = UIA_PropertyIds.UIA_StylesStyleIdPropertyId,
        StylesStyleName = UIA_PropertyIds.UIA_StylesStyleNamePropertyId,
        TableColumnHeaders = UIA_PropertyIds.UIA_TableColumnHeadersPropertyId,
        TableItemColumnHeaderItems = UIA_PropertyIds.UIA_TableItemColumnHeaderItemsPropertyId,
        TableRowHeaders = UIA_PropertyIds.UIA_TableRowHeadersPropertyId,
        TableRowOrColumnMajor = UIA_PropertyIds.UIA_TableRowOrColumnMajorPropertyId,
        TableItemRowHeaderItems = UIA_PropertyIds.UIA_TableItemRowHeaderItemsPropertyId,
        ToggleToggleState = UIA_PropertyIds.UIA_ToggleToggleStatePropertyId,
        TransformCanMove = UIA_PropertyIds.UIA_TransformCanMovePropertyId,
        TransformCanResize = UIA_PropertyIds.UIA_TransformCanResizePropertyId,
        TransformCanRotate = UIA_PropertyIds.UIA_TransformCanRotatePropertyId,
        Transform2CanZoom = UIA_PropertyIds.UIA_Transform2CanZoomPropertyId,
        Transform2ZoomLevel = UIA_PropertyIds.UIA_Transform2ZoomLevelPropertyId,
        Transform2ZoomMaximum = UIA_PropertyIds.UIA_Transform2ZoomMaximumPropertyId,
        Transform2ZoomMinimum = UIA_PropertyIds.UIA_Transform2ZoomMinimumPropertyId,
        ValueIsReadOnly = UIA_PropertyIds.UIA_ValueIsReadOnlyPropertyId,
        ValueValue = UIA_PropertyIds.UIA_ValueValuePropertyId,
        WindowCanMaximize = UIA_PropertyIds.UIA_WindowCanMaximizePropertyId,
        WindowCanMinimize = UIA_PropertyIds.UIA_WindowCanMinimizePropertyId,
        WindowIsModal = UIA_PropertyIds.UIA_WindowIsModalPropertyId,
        WindowIsTopmost = UIA_PropertyIds.UIA_WindowIsTopmostPropertyId,
        WindowWindowInteractionState = UIA_PropertyIds.UIA_WindowWindowInteractionStatePropertyId,
        WindowWindowVisualState = UIA_PropertyIds.UIA_WindowWindowVisualStatePropertyId,
    }
}
